name: Shell Commands

on: [push] # Event

jobs: # List of jobs
  run-shell-command:
    runs-on: ubuntu-latest
    steps:  # Steps performe by the job
      - name: ecccho a string
        run: echo "Hello efren"
      - name: multiline script
        run: |
          node --version
          npm --version

